name: Build JAva Project

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn compile
    - run: mvn package
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: Wochenbericht.jar
        path: ./target/Wochenberichte-1.0-SNAPSHOT.jar
